# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I11_t34Z_Ky4Bmxy2DCwhYD8femoXdMG
"""

'''
Que exista UNA sola forma oficial de:

limpiar

transformar

preparar features

Y que esa misma lógica se use en:

notebooks

entrenamiento

FastAPI (producción)
'''

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#funcion de limpieza

def clean_data(df: pd.DataFrame) -> pd.DataFrame:

    df = df.copy()
    df = df[df["Cancelled"] == 0]
    return df

#Target
def create_target(df: pd.DataFrame, delay_threshold: int = 15) -> pd.DataFrame:

    df = df.copy()
    df["is_delayed"] = (df["ArrDelay"] > delay_threshold).astype(int)
    return df

#feature engineering final
def prepare_features(df: pd.DataFrame):

    df = df.copy()

    df["dep_hour"] = df["CRSDepTime"] // 100
    df = df.drop(columns=["CRSDepTime"])

    features = [
        "UniqueCarrier",
        "Origin",
        "Dest",
        "DayOfWeek",
        "dep_hour",
        "Distance",
    ]

    return df[features]

#Construccion del preprocessor
def build_preprocessor():
    categorical_cols = ["UniqueCarrier", "Origin", "Dest", "DayOfWeek"]
    numerical_cols = ["dep_hour", "Distance"]

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
            ("num", "passthrough", numerical_cols),
        ]
    )

    return preprocessor