USE flighton;
CREATE TABLE aeropuertos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    codigo_iata VARCHAR(3) NOT NULL UNIQUE,
    nombre VARCHAR(30) NOT NULL
);
INSERT INTO aeropuertos (codigo_iata, nombre) VALUES
('ABE', 'Allentown'),
('ABI', 'Abilene'),
('ABQ', 'Albuquerque'),
('ABY', 'Albany'),
('ACK', 'Nantucket'),
('ACT', 'Waco'),
('ACV', 'Arcata CA'),
('ACY', 'Atlantic City'),
('ADK', 'Adak Island'),
('ADQ', 'Kodiak'),
('AEX', 'Alexandria'),
('AGS', 'Bush Field'),
('AKN', 'King Salmon'),
('ALB', 'Albany'),
('ALO', 'Waterloo'),
('AMA', 'Amarillo'),
('ANC', 'Anchorage'),
('ASE', 'Aspen'),
('ATL', 'Atlanta'),
('ATW', 'Appleton'),
('AUS', 'Austin'),
('AVL', 'Asheville'),
('AVP', 'Scranton'),
('AZO', 'Kalamazoo'),
('BDL', 'Windsor Locks'),
('BET', 'Bethel'),
('BFL', 'Bakersfield'),
('BGM', 'Binghamton'),
('BGR', 'Bangor'),
('BHM', 'Birmingham'),
('BIL', 'Billings'),
('BIS', 'Bismarck'),
('BJI', 'Bemidji'),
('BLI', 'Bellingham'),
('BMI', 'Bloomington'),
('BNA', 'Nashville'),
('BOI', 'Boise'),
('BOS', 'Boston'),
('BPT', 'Beaumont'),
('BQK', 'Brunswick'),
('BRO', 'Brownsville'),
('BRW', 'Barrow'),
('BTM', 'Butte'),
('BTR', 'Baton Rouge'),
('BTV', 'Burlington'),
('BUF', 'Buffalo'),
('BUR', 'Burbank'),
('BWI', 'Baltimore'),
('BZN', 'Bozeman'),
('CAE', 'Columbia'),
('CAK', 'Akron'),
('CDC', 'Cedar City'),
('CDV', 'Cordova'),
('CEC', 'Crescent City'),
('CHA', 'Chattanooga'),
('CHO', 'Charlottesville VA'),
('CHS', 'Charleston'),
('CIC', 'Chico'),
('CID', 'Cedar Rapids'),
('CLD', 'Carlsbad'),
('CLE', 'Cleveland'),
('CLL', 'College Station'),
('CLT', 'Charlotte'),
('CMH', 'Columbus'),
('CMI', 'Champaign'),
('CMX', 'Hancock'),
('COD', 'Cody'),
('COS', 'Colorado Springs'),
('CPR', 'Casper'),
('CRP', 'Corpus Christi'),
('CRW', 'Charleston'),
('CSG', 'Columbus'),
('CVG', 'Cincinnati'),
('CWA', 'Wassau'),
('CYS', 'Cheyenne'),
('DAB', 'Daytona Beach'),
('DAL', 'Dallas'),
('DAY', 'Dayton'),
('DBQ', 'Dubuque IA'),
('DCA', 'Washington'),
('DEN', 'Denver'),
('DFW', 'Dallas-Fort Worth'),
('DHN', 'Dothan'),
('DLG', 'Dillingham'),
('DLH', 'Duluth'),
('DRO', 'Durango'),
('DSM', 'Des Moines'),
('DTW', 'Detroit'),
('EGE', 'Vail'),
('EKO', 'Elko'),
('ELM', 'Elmira'),
('ELP', 'El Paso'),
('ERI', 'Erie'),
('EUG', 'Eugene'),
('EVV', 'Evansville'),
('EWN', 'New Bern'),
('EWR', 'Newark'),
('EYW', 'Key West'),
('FAI', 'Fairbanks'),
('FAR', 'Fargo'),
('FAT', 'Fresno'),
('FAY', 'Fayetteville'),
('FCA', 'Kalispell'),
('FLG', 'Flagstaff'),
('FLL', 'Fort Lauderdale'),
('FLO', 'Florence'),
('FNT', 'Flint'),
('FSD', 'Sioux Falls'),
('FSM', 'Fort Smith'),
('FWA', 'Fort Wayne'),
('GCC', 'Gillette'),
('GEG', 'Spokane'),
('GFK', 'Grand Forks'),
('GGG', 'Longview'),
('GJT', 'Grand Junction'),
('GNV', 'Gainesville'),
('GPT', 'Gulfport'),
('GRB', 'Green Bay'),
('GRK', 'Killeen'),
('GRR', 'Grand Rapids'),
('GSO', 'Greensboro'),
('GSP', 'Greenville'),
('GST', 'Gustavus'),
('GTF', 'Great Falls'),
('GTR', 'Columbus Mississippi'),
('GUC', 'Gunnison'),
('HDN', 'Hayden'),
('HHH', 'Hilton Head Island'),
('HLN', 'Helena'),
('HNL', 'Honolulu'),
('HOU', 'Houston'),
('HPN', 'White Plains'),
('HRL', 'Harlingen'),
('HSV', 'Huntsville'),
('HTS', 'Huntington'),
('IAD', 'Washington'),
('IAH', 'Houston'),
('ICT', 'Wichita'),
('IDA', 'Idaho Falls'),
('ILM', 'Wilmington'),
('IND', 'Indianapolis'),
('INL', 'International Falls'),
('IPL', 'Imperial'),
('ISP', 'Islip'),
('ITH', 'Ithaca'),
('ITO', 'Hilo'),
('IYK', 'Inyokern'),
('JAC', 'Jacksn Hole'),
('JAN', 'Jackson'),
('JAX', 'Jacksonville'),
('JFK', 'New York'),
('JNU', 'Juneau'),
('KOA', 'Kona'),
('KTN', 'Ketchikan'),
('LAN', 'Lansing'),
('LAS', 'Las Vegas'),
('LAW', 'Lawton'),
('LAX', 'Los Angeles'),
('LBB', 'Lubbock'),
('LCH', 'Lake Charles'),
('LEX', 'Lexington KY'),
('LFT', 'Lafayette'),
('LGA', 'New York'),
('LGB', 'Long Beach'),
('LIH', 'Lihue'),
('LIT', 'Little Rock'),
('LMT', 'Klamath Falls'),
('LNK', 'Lincoln'),
('LRD', 'Laredo'),
('LSE', 'La Crosse'),
('LWB', 'Lewisburg'),
('LWS', 'Lewiston'),
('LYH', 'Lynchburg'),
('MAF', 'Midland'),
('MBS', 'Saginaw'),
('MCI', 'Kansas City'),
('MCN', 'Macon'),
('MCO', 'Orlando'),
('MDT', 'Harrisburg'),
('MDW', 'Chicago'),
('MEI', 'Meridian'),
('MEM', 'Memphis'),
('MFE', 'Mcallen'),
('MFR', 'Medford'),
('MGM', 'MONTGOMERY'),
('MHT', 'Manchester NH'),
('MIA', 'Miami'),
('MKE', 'Milwaukee'),
('MKG', 'Muskegon'),
('MLB', 'Melbourne'),
('MLI', 'Moline'),
('MLU', 'Monroe'),
('MOB', 'Mobile'),
('MOD', 'Modesto'),
('MOT', 'Minot'),
('MQT', 'Gwinn'),
('MRY', 'Monterey'),
('MSN', 'Madison'),
('MSO', 'Missoula'),
('MSP', 'Minneapolis'),
('MSY', 'New Orleans'),
('MTJ', 'Montrose CO'),
('MYR', 'Myrtle Beach'),
('OAJ', 'Jacksonville NC'),
('OAK', 'Oakland'),
('OGD', 'Ogden'),
('OGG', 'Kahului'),
('OKC', 'Oklahoma City'),
('OMA', 'Omaha'),
('OME', 'Nome'),
('ONT', 'Ontario'),
('ORD', 'Chicago'),
('ORF', 'Norfolk'),
('OTH', 'North Bend'),
('OTZ', 'Kotzebue'),
('OXR', 'Oxnard'),
('PBI', 'West Palm Beach'),
('PDX', 'Portland'),
('PFN', 'Panama City'),
('PHF', 'Newport News'),
('PHL', 'Philadelphia'),
('PHX', 'Phoenix'),
('PIA', 'Peoria'),
('PIH', 'Pocatello'),
('PIR', 'Pierre'),
('PIT', 'Pittsburgh'),
('PLN', 'Pellston'),
('PMD', 'Palmdale'),
('PNS', 'Pensacola'),
('PSC', 'Pasco'),
('PSG', 'Petersburg'),
('PSP', 'Palm Springs'),
('PVD', 'Providence'),
('PWM', 'Portland'),
('RAP', 'Rapid City'),
('RDD', 'Redding'),
('RDM', 'Redmond-Bend'),
('RDU', 'Raleigh-durham'),
('RFD', 'Rockford'),
('RHI', 'Rhinelander'),
('RIC', 'Richmond'),
('RKS', 'Rock Springs'),
('RNO', 'Reno'),
('ROA', 'Roanoke VA'),
('ROC', 'Rochester'),
('ROW', 'Roswell'),
('RST', 'Rochester'),
('RSW', 'Fort Myers'),
('SAN', 'San Diego'),
('SAT', 'San Antonio'),
('SAV', 'Savannah'),
('SBA', 'Santa Barbara'),
('SBN', 'South Bend'),
('SBP', 'San Luis Obispo'),
('SCC', 'Deadhorse'),
('SCE', 'State College Pennsylvania'),
('SDF', 'Louisville'),
('SEA', 'Seattle'),
('SFO', 'San Francisco'),
('SGF', 'Springfield'),
('SGU', 'Saint George'),
('SHV', 'Shreveport'),
('SIT', 'Sitka'),
('SJC', 'San Jose'),
('SJT', 'San Angelo'),
('SLC', 'Salt Lake City'),
('SLE', 'Salem'),
('SMF', 'Sacramento'),
('SMX', 'Santa Maria'),
('SNA', 'Santa Ana'),
('SPI', 'Springfield'),
('SPS', 'Wichita Falls'),
('SRQ', 'Sarasota'),
('STL', 'St. Louis'),
('SUN', 'Hailey'),
('SUX', 'Sioux City'),
('SWF', 'Newburgh'),
('SYR', 'Syracuse'),
('TEX', 'Telluride'),
('TLH', 'Tallahassee'),
('TOL', 'Toledo'),
('TPA', 'Tampa'),
('TRI', 'BRISTOL'),
('TUL', 'Tulsa'),
('TUP', 'Tupelo'),
('TUS', 'Tucson'),
('TVC', 'Traverse City'),
('TWF', 'Twin Falls'),
('TXK', 'Texarkana'),
('TYR', 'Tyler'),
('TYS', 'Knoxville'),
('VLD', 'Valdosta'),
('VPS', 'Valparaiso'),
('WRG', 'Wrangell'),
('WYS', 'West Yellowstone'),
('XNA', 'Bentonville'),
('YAK', 'Yakutat'),
('YKM', 'Yakima'),
('YUM', 'Yuma');
