# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121rybVwk1MaDrHSQ2Y2F1rmX8ls6E2OL

main.py

Punto de entrada de la FastAPI.

Contiene:
- Inicialización de la app
- Endpoint /predict
- Integración con el modelo entrenado
"
"""